version: '3.8'

services:
  redis-prd:
    container_name: redis-prd
    image: arm64v8/redis
    hostname: redis-prd
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    environment:
      - REDIS_PASSWORD=1234
    ports:
      - "16379:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - stg-network

  mariadb-prd:
    container_name: mariadb-prd
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=rootdb
      - MYSQL_USER=mkkang
      - MYSQL_PASSWORD=1234
    ports:
      - "13306:3306"
    networks:
      - stg-network

networks:
  stg-network:
    name: stg-network
    driver: bridge

# docker-compose -f stage/docker-compose-db.yml build
# docker-compose -f stage/docker-compose-db.yml up --build -d