version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: dev-redis
    environment:
      - REDIS_PASSWORD=1234
    ports:
      - "6379:6379"  # 호스트의 6379 포트를 컨테이너의 6379 포트에 매핑
    networks:
      - mkkang-network

  mariadb:
    image: mariadb:latest
    container_name: dev-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rootdb
      - MYSQL_USER=mkkang
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"  # 호스트의 6379 포트를 컨테이너의 6379 포트에 매핑
    networks:
      - mkkang-network

networks:
  mkkang-network:
    driver: bridge

# docker-compose -f develop/docker-compose-db.yml build
# docker-compose -f develop/docker-compose-db.yml up --build -d